Serial.print(F("DIV_771 "));
testCheckSum(TEST_NATIVE_DIV(771));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(771));
Serial.println("");
Serial.print(F("DIV_772 "));
testCheckSum(TEST_NATIVE_DIV(772));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(772));
Serial.println("");
Serial.print(F("DIV_773 "));
testCheckSum(TEST_NATIVE_DIV(773));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(773));
Serial.println("");
Serial.print(F("DIV_774 "));
testCheckSum(TEST_NATIVE_DIV(774));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(774));
Serial.println("");
Serial.print(F("DIV_775 "));
testCheckSum(TEST_NATIVE_DIV(775));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(775));
Serial.println("");
Serial.print(F("DIV_776 "));
testCheckSum(TEST_NATIVE_DIV(776));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(776));
Serial.println("");
Serial.print(F("DIV_777 "));
testCheckSum(TEST_NATIVE_DIV(777));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(777));
Serial.println("");
Serial.print(F("DIV_778 "));
testCheckSum(TEST_NATIVE_DIV(778));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(778));
Serial.println("");
Serial.print(F("DIV_779 "));
testCheckSum(TEST_NATIVE_DIV(779));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(779));
Serial.println("");
Serial.print(F("DIV_780 "));
testCheckSum(TEST_NATIVE_DIV(780));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(780));
Serial.println("");
Serial.print(F("DIV_781 "));
testCheckSum(TEST_NATIVE_DIV(781));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(781));
Serial.println("");
Serial.print(F("DIV_782 "));
testCheckSum(TEST_NATIVE_DIV(782));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(782));
Serial.println("");
Serial.print(F("DIV_783 "));
testCheckSum(TEST_NATIVE_DIV(783));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(783));
Serial.println("");
Serial.print(F("DIV_784 "));
testCheckSum(TEST_NATIVE_DIV(784));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(784));
Serial.println("");
Serial.print(F("DIV_785 "));
testCheckSum(TEST_NATIVE_DIV(785));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(785));
Serial.println("");
Serial.print(F("DIV_786 "));
testCheckSum(TEST_NATIVE_DIV(786));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(786));
Serial.println("");
Serial.print(F("DIV_787 "));
testCheckSum(TEST_NATIVE_DIV(787));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(787));
Serial.println("");
Serial.print(F("DIV_788 "));
testCheckSum(TEST_NATIVE_DIV(788));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(788));
Serial.println("");
Serial.print(F("DIV_789 "));
testCheckSum(TEST_NATIVE_DIV(789));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(789));
Serial.println("");
Serial.print(F("DIV_790 "));
testCheckSum(TEST_NATIVE_DIV(790));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(790));
Serial.println("");
Serial.print(F("DIV_791 "));
testCheckSum(TEST_NATIVE_DIV(791));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(791));
Serial.println("");
Serial.print(F("DIV_792 "));
testCheckSum(TEST_NATIVE_DIV(792));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(792));
Serial.println("");
Serial.print(F("DIV_793 "));
testCheckSum(TEST_NATIVE_DIV(793));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(793));
Serial.println("");
Serial.print(F("DIV_794 "));
testCheckSum(TEST_NATIVE_DIV(794));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(794));
Serial.println("");
Serial.print(F("DIV_795 "));
testCheckSum(TEST_NATIVE_DIV(795));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(795));
Serial.println("");
Serial.print(F("DIV_796 "));
testCheckSum(TEST_NATIVE_DIV(796));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(796));
Serial.println("");
Serial.print(F("DIV_797 "));
testCheckSum(TEST_NATIVE_DIV(797));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(797));
Serial.println("");
Serial.print(F("DIV_798 "));
testCheckSum(TEST_NATIVE_DIV(798));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(798));
Serial.println("");
Serial.print(F("DIV_799 "));
testCheckSum(TEST_NATIVE_DIV(799));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(799));
Serial.println("");
Serial.print(F("DIV_800 "));
testCheckSum(TEST_NATIVE_DIV(800));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(800));
Serial.println("");
Serial.print(F("DIV_801 "));
testCheckSum(TEST_NATIVE_DIV(801));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(801));
Serial.println("");
Serial.print(F("DIV_802 "));
testCheckSum(TEST_NATIVE_DIV(802));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(802));
Serial.println("");
Serial.print(F("DIV_803 "));
testCheckSum(TEST_NATIVE_DIV(803));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(803));
Serial.println("");
Serial.print(F("DIV_804 "));
testCheckSum(TEST_NATIVE_DIV(804));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(804));
Serial.println("");
Serial.print(F("DIV_805 "));
testCheckSum(TEST_NATIVE_DIV(805));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(805));
Serial.println("");
Serial.print(F("DIV_806 "));
testCheckSum(TEST_NATIVE_DIV(806));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(806));
Serial.println("");
Serial.print(F("DIV_807 "));
testCheckSum(TEST_NATIVE_DIV(807));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(807));
Serial.println("");
Serial.print(F("DIV_808 "));
testCheckSum(TEST_NATIVE_DIV(808));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(808));
Serial.println("");
Serial.print(F("DIV_809 "));
testCheckSum(TEST_NATIVE_DIV(809));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(809));
Serial.println("");
Serial.print(F("DIV_810 "));
testCheckSum(TEST_NATIVE_DIV(810));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(810));
Serial.println("");
Serial.print(F("DIV_811 "));
testCheckSum(TEST_NATIVE_DIV(811));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(811));
Serial.println("");
Serial.print(F("DIV_812 "));
testCheckSum(TEST_NATIVE_DIV(812));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(812));
Serial.println("");
Serial.print(F("DIV_813 "));
testCheckSum(TEST_NATIVE_DIV(813));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(813));
Serial.println("");
Serial.print(F("DIV_814 "));
testCheckSum(TEST_NATIVE_DIV(814));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(814));
Serial.println("");
Serial.print(F("DIV_815 "));
testCheckSum(TEST_NATIVE_DIV(815));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(815));
Serial.println("");
Serial.print(F("DIV_816 "));
testCheckSum(TEST_NATIVE_DIV(816));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(816));
Serial.println("");
Serial.print(F("DIV_817 "));
testCheckSum(TEST_NATIVE_DIV(817));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(817));
Serial.println("");
Serial.print(F("DIV_818 "));
testCheckSum(TEST_NATIVE_DIV(818));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(818));
Serial.println("");
Serial.print(F("DIV_819 "));
testCheckSum(TEST_NATIVE_DIV(819));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(819));
Serial.println("");
Serial.print(F("DIV_820 "));
testCheckSum(TEST_NATIVE_DIV(820));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(820));
Serial.println("");
Serial.print(F("DIV_821 "));
testCheckSum(TEST_NATIVE_DIV(821));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(821));
Serial.println("");
Serial.print(F("DIV_822 "));
testCheckSum(TEST_NATIVE_DIV(822));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(822));
Serial.println("");
Serial.print(F("DIV_823 "));
testCheckSum(TEST_NATIVE_DIV(823));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(823));
Serial.println("");
Serial.print(F("DIV_824 "));
testCheckSum(TEST_NATIVE_DIV(824));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(824));
Serial.println("");
Serial.print(F("DIV_825 "));
testCheckSum(TEST_NATIVE_DIV(825));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(825));
Serial.println("");
Serial.print(F("DIV_826 "));
testCheckSum(TEST_NATIVE_DIV(826));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(826));
Serial.println("");
Serial.print(F("DIV_827 "));
testCheckSum(TEST_NATIVE_DIV(827));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(827));
Serial.println("");
Serial.print(F("DIV_828 "));
testCheckSum(TEST_NATIVE_DIV(828));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(828));
Serial.println("");
Serial.print(F("DIV_829 "));
testCheckSum(TEST_NATIVE_DIV(829));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(829));
Serial.println("");
Serial.print(F("DIV_830 "));
testCheckSum(TEST_NATIVE_DIV(830));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(830));
Serial.println("");
Serial.print(F("DIV_831 "));
testCheckSum(TEST_NATIVE_DIV(831));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(831));
Serial.println("");
Serial.print(F("DIV_832 "));
testCheckSum(TEST_NATIVE_DIV(832));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(832));
Serial.println("");
Serial.print(F("DIV_833 "));
testCheckSum(TEST_NATIVE_DIV(833));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(833));
Serial.println("");
Serial.print(F("DIV_834 "));
testCheckSum(TEST_NATIVE_DIV(834));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(834));
Serial.println("");
Serial.print(F("DIV_835 "));
testCheckSum(TEST_NATIVE_DIV(835));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(835));
Serial.println("");
Serial.print(F("DIV_836 "));
testCheckSum(TEST_NATIVE_DIV(836));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(836));
Serial.println("");
Serial.print(F("DIV_837 "));
testCheckSum(TEST_NATIVE_DIV(837));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(837));
Serial.println("");
Serial.print(F("DIV_838 "));
testCheckSum(TEST_NATIVE_DIV(838));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(838));
Serial.println("");
Serial.print(F("DIV_839 "));
testCheckSum(TEST_NATIVE_DIV(839));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(839));
Serial.println("");
Serial.print(F("DIV_840 "));
testCheckSum(TEST_NATIVE_DIV(840));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(840));
Serial.println("");
Serial.print(F("DIV_841 "));
testCheckSum(TEST_NATIVE_DIV(841));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(841));
Serial.println("");
Serial.print(F("DIV_842 "));
testCheckSum(TEST_NATIVE_DIV(842));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(842));
Serial.println("");
Serial.print(F("DIV_843 "));
testCheckSum(TEST_NATIVE_DIV(843));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(843));
Serial.println("");
Serial.print(F("DIV_844 "));
testCheckSum(TEST_NATIVE_DIV(844));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(844));
Serial.println("");
Serial.print(F("DIV_845 "));
testCheckSum(TEST_NATIVE_DIV(845));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(845));
Serial.println("");
Serial.print(F("DIV_846 "));
testCheckSum(TEST_NATIVE_DIV(846));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(846));
Serial.println("");
Serial.print(F("DIV_847 "));
testCheckSum(TEST_NATIVE_DIV(847));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(847));
Serial.println("");
Serial.print(F("DIV_848 "));
testCheckSum(TEST_NATIVE_DIV(848));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(848));
Serial.println("");
Serial.print(F("DIV_849 "));
testCheckSum(TEST_NATIVE_DIV(849));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(849));
Serial.println("");
Serial.print(F("DIV_850 "));
testCheckSum(TEST_NATIVE_DIV(850));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(850));
Serial.println("");
Serial.print(F("DIV_851 "));
testCheckSum(TEST_NATIVE_DIV(851));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(851));
Serial.println("");
Serial.print(F("DIV_852 "));
testCheckSum(TEST_NATIVE_DIV(852));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(852));
Serial.println("");
Serial.print(F("DIV_853 "));
testCheckSum(TEST_NATIVE_DIV(853));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(853));
Serial.println("");
Serial.print(F("DIV_854 "));
testCheckSum(TEST_NATIVE_DIV(854));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(854));
Serial.println("");
Serial.print(F("DIV_855 "));
testCheckSum(TEST_NATIVE_DIV(855));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(855));
Serial.println("");
Serial.print(F("DIV_856 "));
testCheckSum(TEST_NATIVE_DIV(856));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(856));
Serial.println("");
Serial.print(F("DIV_857 "));
testCheckSum(TEST_NATIVE_DIV(857));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(857));
Serial.println("");
Serial.print(F("DIV_858 "));
testCheckSum(TEST_NATIVE_DIV(858));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(858));
Serial.println("");
Serial.print(F("DIV_859 "));
testCheckSum(TEST_NATIVE_DIV(859));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(859));
Serial.println("");
Serial.print(F("DIV_860 "));
testCheckSum(TEST_NATIVE_DIV(860));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(860));
Serial.println("");
Serial.print(F("DIV_861 "));
testCheckSum(TEST_NATIVE_DIV(861));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(861));
Serial.println("");
Serial.print(F("DIV_862 "));
testCheckSum(TEST_NATIVE_DIV(862));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(862));
Serial.println("");
Serial.print(F("DIV_863 "));
testCheckSum(TEST_NATIVE_DIV(863));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(863));
Serial.println("");
Serial.print(F("DIV_864 "));
testCheckSum(TEST_NATIVE_DIV(864));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(864));
Serial.println("");
Serial.print(F("DIV_865 "));
testCheckSum(TEST_NATIVE_DIV(865));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(865));
Serial.println("");
Serial.print(F("DIV_866 "));
testCheckSum(TEST_NATIVE_DIV(866));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(866));
Serial.println("");
Serial.print(F("DIV_867 "));
testCheckSum(TEST_NATIVE_DIV(867));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(867));
Serial.println("");
Serial.print(F("DIV_868 "));
testCheckSum(TEST_NATIVE_DIV(868));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(868));
Serial.println("");
Serial.print(F("DIV_869 "));
testCheckSum(TEST_NATIVE_DIV(869));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(869));
Serial.println("");
Serial.print(F("DIV_870 "));
testCheckSum(TEST_NATIVE_DIV(870));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(870));
Serial.println("");
Serial.print(F("DIV_871 "));
testCheckSum(TEST_NATIVE_DIV(871));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(871));
Serial.println("");
Serial.print(F("DIV_872 "));
testCheckSum(TEST_NATIVE_DIV(872));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(872));
Serial.println("");
Serial.print(F("DIV_873 "));
testCheckSum(TEST_NATIVE_DIV(873));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(873));
Serial.println("");
Serial.print(F("DIV_874 "));
testCheckSum(TEST_NATIVE_DIV(874));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(874));
Serial.println("");
Serial.print(F("DIV_875 "));
testCheckSum(TEST_NATIVE_DIV(875));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(875));
Serial.println("");
Serial.print(F("DIV_876 "));
testCheckSum(TEST_NATIVE_DIV(876));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(876));
Serial.println("");
Serial.print(F("DIV_877 "));
testCheckSum(TEST_NATIVE_DIV(877));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(877));
Serial.println("");
Serial.print(F("DIV_878 "));
testCheckSum(TEST_NATIVE_DIV(878));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(878));
Serial.println("");
Serial.print(F("DIV_879 "));
testCheckSum(TEST_NATIVE_DIV(879));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(879));
Serial.println("");
Serial.print(F("DIV_880 "));
testCheckSum(TEST_NATIVE_DIV(880));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(880));
Serial.println("");
Serial.print(F("DIV_881 "));
testCheckSum(TEST_NATIVE_DIV(881));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(881));
Serial.println("");
Serial.print(F("DIV_882 "));
testCheckSum(TEST_NATIVE_DIV(882));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(882));
Serial.println("");
Serial.print(F("DIV_883 "));
testCheckSum(TEST_NATIVE_DIV(883));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(883));
Serial.println("");
Serial.print(F("DIV_884 "));
testCheckSum(TEST_NATIVE_DIV(884));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(884));
Serial.println("");
Serial.print(F("DIV_885 "));
testCheckSum(TEST_NATIVE_DIV(885));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(885));
Serial.println("");
Serial.print(F("DIV_886 "));
testCheckSum(TEST_NATIVE_DIV(886));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(886));
Serial.println("");
Serial.print(F("DIV_887 "));
testCheckSum(TEST_NATIVE_DIV(887));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(887));
Serial.println("");
Serial.print(F("DIV_888 "));
testCheckSum(TEST_NATIVE_DIV(888));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(888));
Serial.println("");
Serial.print(F("DIV_889 "));
testCheckSum(TEST_NATIVE_DIV(889));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(889));
Serial.println("");
Serial.print(F("DIV_890 "));
testCheckSum(TEST_NATIVE_DIV(890));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(890));
Serial.println("");
Serial.print(F("DIV_891 "));
testCheckSum(TEST_NATIVE_DIV(891));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(891));
Serial.println("");
Serial.print(F("DIV_892 "));
testCheckSum(TEST_NATIVE_DIV(892));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(892));
Serial.println("");
Serial.print(F("DIV_893 "));
testCheckSum(TEST_NATIVE_DIV(893));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(893));
Serial.println("");
Serial.print(F("DIV_894 "));
testCheckSum(TEST_NATIVE_DIV(894));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(894));
Serial.println("");
Serial.print(F("DIV_895 "));
testCheckSum(TEST_NATIVE_DIV(895));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(895));
Serial.println("");
Serial.print(F("DIV_896 "));
testCheckSum(TEST_NATIVE_DIV(896));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(896));
Serial.println("");
Serial.print(F("DIV_897 "));
testCheckSum(TEST_NATIVE_DIV(897));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(897));
Serial.println("");
Serial.print(F("DIV_898 "));
testCheckSum(TEST_NATIVE_DIV(898));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(898));
Serial.println("");
Serial.print(F("DIV_899 "));
testCheckSum(TEST_NATIVE_DIV(899));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(899));
Serial.println("");
Serial.print(F("DIV_900 "));
testCheckSum(TEST_NATIVE_DIV(900));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(900));
Serial.println("");
Serial.print(F("DIV_901 "));
testCheckSum(TEST_NATIVE_DIV(901));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(901));
Serial.println("");
Serial.print(F("DIV_902 "));
testCheckSum(TEST_NATIVE_DIV(902));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(902));
Serial.println("");
Serial.print(F("DIV_903 "));
testCheckSum(TEST_NATIVE_DIV(903));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(903));
Serial.println("");
Serial.print(F("DIV_904 "));
testCheckSum(TEST_NATIVE_DIV(904));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(904));
Serial.println("");
Serial.print(F("DIV_905 "));
testCheckSum(TEST_NATIVE_DIV(905));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(905));
Serial.println("");
Serial.print(F("DIV_906 "));
testCheckSum(TEST_NATIVE_DIV(906));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(906));
Serial.println("");
Serial.print(F("DIV_907 "));
testCheckSum(TEST_NATIVE_DIV(907));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(907));
Serial.println("");
Serial.print(F("DIV_908 "));
testCheckSum(TEST_NATIVE_DIV(908));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(908));
Serial.println("");
Serial.print(F("DIV_909 "));
testCheckSum(TEST_NATIVE_DIV(909));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(909));
Serial.println("");
Serial.print(F("DIV_910 "));
testCheckSum(TEST_NATIVE_DIV(910));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(910));
Serial.println("");
Serial.print(F("DIV_911 "));
testCheckSum(TEST_NATIVE_DIV(911));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(911));
Serial.println("");
Serial.print(F("DIV_912 "));
testCheckSum(TEST_NATIVE_DIV(912));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(912));
Serial.println("");
Serial.print(F("DIV_913 "));
testCheckSum(TEST_NATIVE_DIV(913));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(913));
Serial.println("");
Serial.print(F("DIV_914 "));
testCheckSum(TEST_NATIVE_DIV(914));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(914));
Serial.println("");
Serial.print(F("DIV_915 "));
testCheckSum(TEST_NATIVE_DIV(915));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(915));
Serial.println("");
Serial.print(F("DIV_916 "));
testCheckSum(TEST_NATIVE_DIV(916));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(916));
Serial.println("");
Serial.print(F("DIV_917 "));
testCheckSum(TEST_NATIVE_DIV(917));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(917));
Serial.println("");
Serial.print(F("DIV_918 "));
testCheckSum(TEST_NATIVE_DIV(918));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(918));
Serial.println("");
Serial.print(F("DIV_919 "));
testCheckSum(TEST_NATIVE_DIV(919));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(919));
Serial.println("");
Serial.print(F("DIV_920 "));
testCheckSum(TEST_NATIVE_DIV(920));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(920));
Serial.println("");
Serial.print(F("DIV_921 "));
testCheckSum(TEST_NATIVE_DIV(921));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(921));
Serial.println("");
Serial.print(F("DIV_922 "));
testCheckSum(TEST_NATIVE_DIV(922));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(922));
Serial.println("");
Serial.print(F("DIV_923 "));
testCheckSum(TEST_NATIVE_DIV(923));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(923));
Serial.println("");
Serial.print(F("DIV_924 "));
testCheckSum(TEST_NATIVE_DIV(924));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(924));
Serial.println("");
Serial.print(F("DIV_925 "));
testCheckSum(TEST_NATIVE_DIV(925));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(925));
Serial.println("");
Serial.print(F("DIV_926 "));
testCheckSum(TEST_NATIVE_DIV(926));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(926));
Serial.println("");
Serial.print(F("DIV_927 "));
testCheckSum(TEST_NATIVE_DIV(927));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(927));
Serial.println("");
Serial.print(F("DIV_928 "));
testCheckSum(TEST_NATIVE_DIV(928));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(928));
Serial.println("");
Serial.print(F("DIV_929 "));
testCheckSum(TEST_NATIVE_DIV(929));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(929));
Serial.println("");
Serial.print(F("DIV_930 "));
testCheckSum(TEST_NATIVE_DIV(930));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(930));
Serial.println("");
Serial.print(F("DIV_931 "));
testCheckSum(TEST_NATIVE_DIV(931));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(931));
Serial.println("");
Serial.print(F("DIV_932 "));
testCheckSum(TEST_NATIVE_DIV(932));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(932));
Serial.println("");
Serial.print(F("DIV_933 "));
testCheckSum(TEST_NATIVE_DIV(933));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(933));
Serial.println("");
Serial.print(F("DIV_934 "));
testCheckSum(TEST_NATIVE_DIV(934));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(934));
Serial.println("");
Serial.print(F("DIV_935 "));
testCheckSum(TEST_NATIVE_DIV(935));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(935));
Serial.println("");
Serial.print(F("DIV_936 "));
testCheckSum(TEST_NATIVE_DIV(936));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(936));
Serial.println("");
Serial.print(F("DIV_937 "));
testCheckSum(TEST_NATIVE_DIV(937));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(937));
Serial.println("");
Serial.print(F("DIV_938 "));
testCheckSum(TEST_NATIVE_DIV(938));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(938));
Serial.println("");
Serial.print(F("DIV_939 "));
testCheckSum(TEST_NATIVE_DIV(939));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(939));
Serial.println("");
Serial.print(F("DIV_940 "));
testCheckSum(TEST_NATIVE_DIV(940));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(940));
Serial.println("");
Serial.print(F("DIV_941 "));
testCheckSum(TEST_NATIVE_DIV(941));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(941));
Serial.println("");
Serial.print(F("DIV_942 "));
testCheckSum(TEST_NATIVE_DIV(942));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(942));
Serial.println("");
Serial.print(F("DIV_943 "));
testCheckSum(TEST_NATIVE_DIV(943));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(943));
Serial.println("");
Serial.print(F("DIV_944 "));
testCheckSum(TEST_NATIVE_DIV(944));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(944));
Serial.println("");
Serial.print(F("DIV_945 "));
testCheckSum(TEST_NATIVE_DIV(945));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(945));
Serial.println("");
Serial.print(F("DIV_946 "));
testCheckSum(TEST_NATIVE_DIV(946));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(946));
Serial.println("");
Serial.print(F("DIV_947 "));
testCheckSum(TEST_NATIVE_DIV(947));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(947));
Serial.println("");
Serial.print(F("DIV_948 "));
testCheckSum(TEST_NATIVE_DIV(948));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(948));
Serial.println("");
Serial.print(F("DIV_949 "));
testCheckSum(TEST_NATIVE_DIV(949));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(949));
Serial.println("");
Serial.print(F("DIV_950 "));
testCheckSum(TEST_NATIVE_DIV(950));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(950));
Serial.println("");
Serial.print(F("DIV_951 "));
testCheckSum(TEST_NATIVE_DIV(951));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(951));
Serial.println("");
Serial.print(F("DIV_952 "));
testCheckSum(TEST_NATIVE_DIV(952));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(952));
Serial.println("");
Serial.print(F("DIV_953 "));
testCheckSum(TEST_NATIVE_DIV(953));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(953));
Serial.println("");
Serial.print(F("DIV_954 "));
testCheckSum(TEST_NATIVE_DIV(954));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(954));
Serial.println("");
Serial.print(F("DIV_955 "));
testCheckSum(TEST_NATIVE_DIV(955));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(955));
Serial.println("");
Serial.print(F("DIV_956 "));
testCheckSum(TEST_NATIVE_DIV(956));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(956));
Serial.println("");
Serial.print(F("DIV_957 "));
testCheckSum(TEST_NATIVE_DIV(957));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(957));
Serial.println("");
Serial.print(F("DIV_958 "));
testCheckSum(TEST_NATIVE_DIV(958));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(958));
Serial.println("");
Serial.print(F("DIV_959 "));
testCheckSum(TEST_NATIVE_DIV(959));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(959));
Serial.println("");
Serial.print(F("DIV_960 "));
testCheckSum(TEST_NATIVE_DIV(960));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(960));
Serial.println("");
Serial.print(F("DIV_961 "));
testCheckSum(TEST_NATIVE_DIV(961));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(961));
Serial.println("");
Serial.print(F("DIV_962 "));
testCheckSum(TEST_NATIVE_DIV(962));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(962));
Serial.println("");
Serial.print(F("DIV_963 "));
testCheckSum(TEST_NATIVE_DIV(963));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(963));
Serial.println("");
Serial.print(F("DIV_964 "));
testCheckSum(TEST_NATIVE_DIV(964));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(964));
Serial.println("");
Serial.print(F("DIV_965 "));
testCheckSum(TEST_NATIVE_DIV(965));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(965));
Serial.println("");
Serial.print(F("DIV_966 "));
testCheckSum(TEST_NATIVE_DIV(966));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(966));
Serial.println("");
Serial.print(F("DIV_967 "));
testCheckSum(TEST_NATIVE_DIV(967));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(967));
Serial.println("");
Serial.print(F("DIV_968 "));
testCheckSum(TEST_NATIVE_DIV(968));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(968));
Serial.println("");
Serial.print(F("DIV_969 "));
testCheckSum(TEST_NATIVE_DIV(969));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(969));
Serial.println("");
Serial.print(F("DIV_970 "));
testCheckSum(TEST_NATIVE_DIV(970));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(970));
Serial.println("");
Serial.print(F("DIV_971 "));
testCheckSum(TEST_NATIVE_DIV(971));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(971));
Serial.println("");
Serial.print(F("DIV_972 "));
testCheckSum(TEST_NATIVE_DIV(972));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(972));
Serial.println("");
Serial.print(F("DIV_973 "));
testCheckSum(TEST_NATIVE_DIV(973));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(973));
Serial.println("");
Serial.print(F("DIV_974 "));
testCheckSum(TEST_NATIVE_DIV(974));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(974));
Serial.println("");
Serial.print(F("DIV_975 "));
testCheckSum(TEST_NATIVE_DIV(975));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(975));
Serial.println("");
Serial.print(F("DIV_976 "));
testCheckSum(TEST_NATIVE_DIV(976));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(976));
Serial.println("");
Serial.print(F("DIV_977 "));
testCheckSum(TEST_NATIVE_DIV(977));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(977));
Serial.println("");
Serial.print(F("DIV_978 "));
testCheckSum(TEST_NATIVE_DIV(978));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(978));
Serial.println("");
Serial.print(F("DIV_979 "));
testCheckSum(TEST_NATIVE_DIV(979));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(979));
Serial.println("");
Serial.print(F("DIV_980 "));
testCheckSum(TEST_NATIVE_DIV(980));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(980));
Serial.println("");
Serial.print(F("DIV_981 "));
testCheckSum(TEST_NATIVE_DIV(981));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(981));
Serial.println("");
Serial.print(F("DIV_982 "));
testCheckSum(TEST_NATIVE_DIV(982));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(982));
Serial.println("");
Serial.print(F("DIV_983 "));
testCheckSum(TEST_NATIVE_DIV(983));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(983));
Serial.println("");
Serial.print(F("DIV_984 "));
testCheckSum(TEST_NATIVE_DIV(984));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(984));
Serial.println("");
Serial.print(F("DIV_985 "));
testCheckSum(TEST_NATIVE_DIV(985));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(985));
Serial.println("");
Serial.print(F("DIV_986 "));
testCheckSum(TEST_NATIVE_DIV(986));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(986));
Serial.println("");
Serial.print(F("DIV_987 "));
testCheckSum(TEST_NATIVE_DIV(987));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(987));
Serial.println("");
Serial.print(F("DIV_988 "));
testCheckSum(TEST_NATIVE_DIV(988));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(988));
Serial.println("");
Serial.print(F("DIV_989 "));
testCheckSum(TEST_NATIVE_DIV(989));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(989));
Serial.println("");
Serial.print(F("DIV_990 "));
testCheckSum(TEST_NATIVE_DIV(990));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(990));
Serial.println("");
Serial.print(F("DIV_991 "));
testCheckSum(TEST_NATIVE_DIV(991));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(991));
Serial.println("");
Serial.print(F("DIV_992 "));
testCheckSum(TEST_NATIVE_DIV(992));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(992));
Serial.println("");
Serial.print(F("DIV_993 "));
testCheckSum(TEST_NATIVE_DIV(993));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(993));
Serial.println("");
Serial.print(F("DIV_994 "));
testCheckSum(TEST_NATIVE_DIV(994));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(994));
Serial.println("");
Serial.print(F("DIV_995 "));
testCheckSum(TEST_NATIVE_DIV(995));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(995));
Serial.println("");
Serial.print(F("DIV_996 "));
testCheckSum(TEST_NATIVE_DIV(996));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(996));
Serial.println("");
Serial.print(F("DIV_997 "));
testCheckSum(TEST_NATIVE_DIV(997));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(997));
Serial.println("");
Serial.print(F("DIV_998 "));
testCheckSum(TEST_NATIVE_DIV(998));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(998));
Serial.println("");
Serial.print(F("DIV_999 "));
testCheckSum(TEST_NATIVE_DIV(999));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(999));
Serial.println("");
Serial.print(F("DIV_1000 "));
testCheckSum(TEST_NATIVE_DIV(1000));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(1000));
Serial.println("");
Serial.print(F("DIV_1001 "));
testCheckSum(TEST_NATIVE_DIV(1001));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(1001));
Serial.println("");
Serial.print(F("DIV_1002 "));
testCheckSum(TEST_NATIVE_DIV(1002));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(1002));
Serial.println("");
Serial.print(F("DIV_1003 "));
testCheckSum(TEST_NATIVE_DIV(1003));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(1003));
Serial.println("");
Serial.print(F("DIV_1004 "));
testCheckSum(TEST_NATIVE_DIV(1004));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(1004));
Serial.println("");
Serial.print(F("DIV_1005 "));
testCheckSum(TEST_NATIVE_DIV(1005));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(1005));
Serial.println("");
Serial.print(F("DIV_1006 "));
testCheckSum(TEST_NATIVE_DIV(1006));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(1006));
Serial.println("");
Serial.print(F("DIV_1007 "));
testCheckSum(TEST_NATIVE_DIV(1007));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(1007));
Serial.println("");
Serial.print(F("DIV_1008 "));
testCheckSum(TEST_NATIVE_DIV(1008));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(1008));
Serial.println("");
Serial.print(F("DIV_1009 "));
testCheckSum(TEST_NATIVE_DIV(1009));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(1009));
Serial.println("");
Serial.print(F("DIV_1010 "));
testCheckSum(TEST_NATIVE_DIV(1010));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(1010));
Serial.println("");
Serial.print(F("DIV_1011 "));
testCheckSum(TEST_NATIVE_DIV(1011));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(1011));
Serial.println("");
Serial.print(F("DIV_1012 "));
testCheckSum(TEST_NATIVE_DIV(1012));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(1012));
Serial.println("");
Serial.print(F("DIV_1013 "));
testCheckSum(TEST_NATIVE_DIV(1013));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(1013));
Serial.println("");
Serial.print(F("DIV_1014 "));
testCheckSum(TEST_NATIVE_DIV(1014));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(1014));
Serial.println("");
Serial.print(F("DIV_1015 "));
testCheckSum(TEST_NATIVE_DIV(1015));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(1015));
Serial.println("");
Serial.print(F("DIV_1016 "));
testCheckSum(TEST_NATIVE_DIV(1016));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(1016));
Serial.println("");
Serial.print(F("DIV_1017 "));
testCheckSum(TEST_NATIVE_DIV(1017));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(1017));
Serial.println("");
Serial.print(F("DIV_1018 "));
testCheckSum(TEST_NATIVE_DIV(1018));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(1018));
Serial.println("");
Serial.print(F("DIV_1019 "));
testCheckSum(TEST_NATIVE_DIV(1019));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(1019));
Serial.println("");
Serial.print(F("DIV_1020 "));
testCheckSum(TEST_NATIVE_DIV(1020));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(1020));
Serial.println("");
Serial.print(F("DIV_1021 "));
testCheckSum(TEST_NATIVE_DIV(1021));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(1021));
Serial.println("");
Serial.print(F("DIV_1022 "));
testCheckSum(TEST_NATIVE_DIV(1022));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(1022));
Serial.println("");
Serial.print(F("DIV_1023 "));
testCheckSum(TEST_NATIVE_DIV(1023));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(1023));
Serial.println("");
Serial.print(F("DIV_1024 "));
testCheckSum(TEST_NATIVE_DIV(1024));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(1024));
Serial.println("");
Serial.print(F("DIV_1025 "));
testCheckSum(TEST_NATIVE_DIV(1025));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(1025));
Serial.println("");
Serial.print(F("DIV_1026 "));
testCheckSum(TEST_NATIVE_DIV(1026));
Serial.print(" ");
testCheckSum(TEST_FAST_DIV(1026));
Serial.println("");
